[[agents]]
name = "snel-defi-assistant"
description = "AI-powered cross-chain DeFi assistant for seamless blockchain operations"
goal = "Help users execute DeFi operations across multiple blockchain networks using natural language commands"
model = "gpt-4"
tools = ["filesystem", "git", "shell", "ripgrep"]

[[agents]]
name = "defi-analyzer"
description = "Analyze DeFi protocols and provide insights on cross-chain operations"
goal = "Analyze DeFi protocols, token swaps, and cross-chain bridging operations"
model = "gpt-4"
tools = ["filesystem", "ripgrep"]

[[agents]]
name = "blockchain-developer"
description = "Assist with blockchain development and smart contract operations"
goal = "Help with blockchain development, smart contract deployment, and Web3 integration"
model = "gpt-4"
tools = ["filesystem", "git", "shell", "ripgrep"]