version: 1

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - API_V1_STR=/api/v1
      - PROJECT_NAME=Stable Snel API
      - REDIS_URL=${REDIS_URL}
      - BRIAN_API_KEY=${BRIAN_API_KEY}
      - BRIAN_API_URL=${BRIAN_API_URL}
      - DISABLE_SSL_VERIFY=false
      - ZEROX_API_KEY=${ZEROX_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - COINGECKO_API_KEY=${COINGECKO_API_KEY}
      - MORALIS_API_KEY=${MORALIS_API_KEY}
      - ALCHEMY_KEY=${ALCHEMY_KEY}
    resources:
      cpu: 0.5
      memory: 1Gi
    scaling:
      min: 1
      max: 3
    health:
      path: /health
      port: 8000
